CXX  = g++ -std=c++11
DIR  = /usr/local
LIBS = -lgecodedriver    -lgecodesearch  \
       -lgecodeminimodel -lgecodeint     \
       -lgecodekernel    -lgecodesupport

p: Queens.cpp
	$(CXX) -I$(DIR)/include -c Queens.cpp
	$(CXX) -L$(DIR)/lib -o Queens Queens.o $(LIBS)
